### ISSUE TITLE
moment error

### ISSUE THREAD

**Issue by Jameshooper** [ikeros/fortumAPI#2]
Hi,

Thanks for making this. 

I tried installing and running, but get the following error.

fortum.getConsumption('my details', moment().startOf('day').subtract(1, 'days'), moment().endOf('day').subtract(1, 'days'), (err, json) => {
           ^

ReferenceError: moment is not defined
    at fortum.login (/fortumAPI-master/main.js:8:12)
    at Request.request.get [as _callback] (/fortumAPI-master/fortum.api.js:188:8)
    at Request.self.callback (/fortumAPI-master/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/fortumAPI-master/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/fortumAPI-master/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)

Any suggestions very much appreciated

**Comment by ikeros** [comment]
Hi,

You are probably not loading moment in your code. Try adding the following line somewhere before actually using moment, if you want to specify times with moment like in the samples.

const moment = require('moment');
